# Generated by Django 4.0.1 on 2022-01-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cnt',
            field=models.IntegerField(max_length=10),
        ),
    ]
