# Generated by Django 4.0.1 on 2022-01-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_alter_course_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('type', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
            ],
            options={
                'db_table': 'army_shop',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='cnt',
            field=models.IntegerField(),
        ),
    ]
